### ISSUE TITLE
Supporting scratches with the same names which have different extensions

### ISSUE THREAD

**Issue by svozniuk** [dkandalov/scratch#28]
Right now if you have a scratch named some.txt then it's not possible to create any of the following some.js, some.java, some.xml and whatever other file named "some" regardless the extension. 
I propose to allow multiple files with the same name if the extensions are different.

The change should be relatively easy to do and I'm ready to implement it myself.

**Comment by dkandalov** [comment]
I agree, it is a UX bug that scratches must have different names.
This would be great, thanks!

In general though I was hoping to try and see if this plugin can be somehow migrated or even completely replaced by built-in scratches in IntelliJ (i.e. in Project View, "Project" dropdown, "Scratches" view).

**Comment by svozniuk** [comment]
Created a PR
