### ISSUE TITLE
Select All does not Work

### ISSUE THREAD

**Issue by fabb** [dkandalov/scratch#34]
Since the latest AppCode EAP (probably IntelliJ too), Select All only works half of the time.

**Comment by dkandalov** [comment]
What do you mean by "Select All"?

**Comment by fabb** [comment]
Cmd+A

**Comment by dkandalov** [comment]
Are you pressing Cmd+A in code editor? 
If yes, why you think this is a problem with the plugin?

**Comment by fabb** [comment]
Yes, in the code editor. I just noticed the issue when in ascratch, but now thinking about it, I don't use select all very much in non-scratch tabs, so maybe it's broken in the IDE and not this plugin :facepalm:. I'll check that.

**Comment by dkandalov** [comment]
Ah, I see, no problem :)

Btw, in `IntelliJ #IU-171.2822.15 built on February 1` on windows "Select All" seems to work fine.

On OSX though I noticed in latest builds some shortcuts don't work anymore. May be JetBrains broke their custom JDK. As a guess, it might be that "Select All" doesn't work only in some keyboard layouts, e.g. if you switch between English and some other language.

**Comment by fabb** [comment]
The strange thing is that it works half of the time, also when choosing Select All from the menu.

**Comment by fabb** [comment]
Ok, it also happens for non-scratches, so I created a bugticket for AppCode: https://youtrack.jetbrains.com/issue/OC-14941
