### ISSUE TITLE
how to disable `ctrl+n` to create new scratch file When scratches list popup

### ISSUE THREAD

**Issue by sunznx** [dkandalov/scratch#40]
In scratches list popup，when I type `ctrl+n`，it will try to create new scratch file，any way to disable this.  this behavior have a conflict as I use emacs keymap

**Comment by dkandalov** [comment]
The shortcut is copied from the built-in `Generate...` action so if you change it, the shortcut in the popup should change as well.

**Comment by sunznx** [comment]
> The shortcut is copied from the built-in `Generate...` action so if you change it, the shortcut in the popup should change as well.

the reason is I removed the default  `Generate...` shortcut，and this plugin set `ctrl+n` as default shortcut

**Comment by dkandalov** [comment]
Yes, it defaults to `ctrl+n` which wasn't the best idea. I'll need to release a new version to fix that :(
